root: true

env:
  commonjs: true
  es6: true
  node: true

extends:
  - eslint:all
  - plugin:prettier/recommended

plugins:
  - prettier
parserOptions:
  'ecmaVersion': 2018

rules:
  no-console: 'off'

  no-debugger: 'off'

  no-useless-constructor:
    - off

  class-methods-use-this:
    - off

  comma-dangle:
    - error
    - never

  complexity:
    - warn
    - max: 25

  capitalized-comments:
    - off

  curly:
    - error
    - multi

  global-require:
    - off

  id-length:
    - error
    - min: 2
      exceptions:
        - e
        - h
        - i
        - x
        - y

  implicit-arrow-linebreak:
    - off

  indent:
    - off
    - 2
    - ignoredNodes:
        - ConditionalExpression

  init-declarations:
    - off

  function-call-argument-newline:
    - error
    - consistent

  line-comment-position:
    - off

  max-statements:
    - warn
    - 25

  new-cap:
    - off

  nonblock-statement-body-position:
    - error
    - any

  no-inline-comments:
    - off

  no-magic-numbers:
    - off

  no-nested-ternary:
    - off

  no-param-reassign:
    - error
    - props: false

  no-plusplus:
    - error
    - allowForLoopAfterthoughts: true

  no-process-env:
    - off

  no-sync:
    - off

  no-ternary:
    - off

  no-undefined:
    - off

  no-unused-vars:
    - off

  no-warning-comments:
    - warn

  object-curly-spacing:
    - off

  one-var:
    - error
    - never

  padded-blocks:
    - error
    - never

  prefer-destructuring:
    - error
    - object: true
      array: false

  prefer-named-capture-group:
    - off

  quotes:
    - error
    - single

  radix:
    - error
    - as-needed

  sort-keys:
    - off

  strict:
    - off

overrides:
  - files:
      - "*.ts"

    extends:
      - plugin:@typescript-eslint/eslint-recommended
      - plugin:@typescript-eslint/recommended
      - prettier/@typescript-eslint

    plugins:
      - "@typescript-eslint"

    parserOptions:
      parser: "@typescript-eslint/parser"

    rules:
      "@typescript-eslint/explicit-function-return-type":
        - warn
        - allowTypedFunctionExpressions: true

      "@typescript-eslint/no-explicit-any": off
