root: true

env:
  es6: true
  node: true

extends:
  - eslint:recommended
  - plugin:prettier/recommended

plugins:
  - prettier

rules:
  comma-dangle:
    - off

  complexity:
    - warn
    - max: 25

  capitalized-comments:
    - off

  curly:
    - error
    - multi

  function-call-argument-newline:
    - error
    - consistent

  global-require:
    - off

  guard-for-in:
    - off

  id-length:
    - error
    - min: 2
      exceptions:
        - i
        - j
        - x
        - y

  implicit-arrow-linebreak:
    - off

  indent:
    - off

  init-declarations:
    - off

  line-comment-position:
    - off

  max-lines:
    - warn
    - 500

  max-lines-per-function:
    - warn
    - 80

  max-statements:
    - warn
    - 25

  new-cap:
    - off

  nonblock-statement-body-position:
    - error
    - any

  no-console:
    - off

  no-debugger:
    - off

  no-inline-comments:
    - off

  no-magic-numbers:
    - off

  no-multi-assign:
    - off

  no-nested-ternary:
    - off

  no-param-reassign:
    - error
    - props: false

  no-plusplus:
    - error
    - allowForLoopAfterthoughts: true

  no-sync:
    - off

  no-ternary:
    - off

  no-underscore-dangle:
    - error
    - allowAfterThis: true

  no-undefined:
    - off

  no-unused-vars:
    - off

  no-warning-comments:
    - warn

  object-curly-spacing:
    - off

  prefer-destructuring:
    - error
    - object: true
      array: false

overrides:
  - files:
      - "*.ts"

    extends:
      - plugin:@typescript-eslint/eslint-recommended
      - plugin:@typescript-eslint/recommended
      - prettier/@typescript-eslint

    plugins:
      - "@typescript-eslint"

    parserOptions:
      parser: "@typescript-eslint/parser"
      project:
        - "./tsconfig.json"

    rules:
      "@typescript-eslint/explicit-function-return-type":
        - warn
        - allowTypedFunctionExpressions: true

      "@typescript-eslint/naming-convention":
        - warn
        - selector: default
          format:
            - camelCase
          leadingUnderscore: allow
          trailingUnderscore: allow

        - selector: variable
          format:
            - camelCase
            - UPPER_CASE
          leadingUnderscore: allow
          trailingUnderscore: allow

        - selector: typeLike
          format:
            - PascalCase

      "@typescript-eslint/no-explicit-any":
        - off
        # - warn
        # - ignoreRestArgs: true

      "@typescript-eslint/no-unsafe-member-access":
        - off
        # - warn

  - files:
      - "**/test/**/*.spec.js"
      - "**/test/**/*.spec.ts"
      - "**/test/**/*.test.js"
      - "**/test/**/*.test.ts"

    env:
      mocha: true
      node: true

    rules:
      id-length: "off"
      max-lines-per-function: "off"
