root: true

env:
  node: true
  es6: true

extends:
  - eslint:all
  - plugin:prettier/recommended

plugins:
  - prettier

parserOptions:
  "ecmaVersion": 2018

rules:
  prettier/prettier: error

  # 自定义
  arrow-parens:
    - error
    - as-needed

  # 'brace-style': ['error', '1tbs', { allowSingleLine: true }]

  comma-dangle:
    - error
    - never

  complexity:
    - warn
    - max: 25

  capitalized-comments:
    - off

  curly:
    - error
    - multi

  implicit-arrow-linebreak:
    - off

  indent:
    - error
    - 2

  init-declarations:
    - off

  function-call-argument-newline:
    - error
    - consistent

  nonblock-statement-body-position:
    - error
    - any
  no-param-reassign:
    - error
    - props: false

  no-plusplus:
    - error
    - allowForLoopAfterthoughts: true

  object-curly-newline:
    - error
    - ExportDeclaration:
        multiline: true
        minProperties: 3
      ImportDeclaration:
        multiline: true
        minProperties: 5
      ObjectExpression:
        multiline: true
      ObjectPattern:
        multiline: true

  object-curly-spacing: "off"

  one-var:
    - error
    - never

  padded-blocks:
    - error
    - never

  quotes:
    - error
    - single
  
  strict:
    - off

  # 暂时禁用的自定义规则
  # 'array-element-newline': ['error', 'consistent']
  # 防止因为自动换行造成的报错
  # 'implicit-arrow-linebreak': ['off', 'beside']
  # 简化代码，忽略迷惑的箭头函数提示
  # 'no-confusing-arrow': 'off'
