# 阻止eslint读取父目录或总配置文件的规则
root: true

# 代码环境
env:
  browser: true
  commonjs: true
  es6: true
  node: true

# 所使用的规则配置
extends:
  - eslint:all
  - plugin:prettier/recommended

# 插件
plugins:
  - prettier

# 解析器选项
parserOptions:
  "ecmaVersion": 2018

rules:
  prettier/prettier: error

  # 自定义
  arrow-parens:
    - error
    - as-needed

  # 'brace-style': ['error', '1tbs', { allowSingleLine: true }]

  comma-dangle:
    - error
    - never

  complexity:
    - warn
    - max: 25

  capitalized-comments:
    - off

  curly:
    - error
    - multi

  global-require:
    - off

  id-length:
    - error
    - min: 2
      exceptions:
        - e
        - h
        - i
        - x
        - y

  implicit-arrow-linebreak:
    - off

  indent:
    - error
    - 2
    - SwitchCase: 1
      flatTernaryExpressions: true

  init-declarations:
    - off

  function-call-argument-newline:
    - error
    - consistent

  line-comment-position:
    - off

  nonblock-statement-body-position:
    - error
    - any

  no-inline-comments:
    - off

  no-magic-numbers:
    - off

  no-nested-ternary:
    - off

  no-param-reassign:
    - error
    - props: false

  no-plusplus:
    - error
    - allowForLoopAfterthoughts: true

  no-ternary:
    - off

  object-curly-spacing: "off"

  one-var:
    - error
    - never

  padded-blocks:
    - error
    - never

  prefer-destructuring:
    - error
    - object: true
      array: false

  prefer-named-capture-group:
    - off

  quotes:
    - error
    - single

  radix:
    - error
    - as-needed

  sort-keys:
    - off

  strict:
    - off
  # 暂时禁用的自定义规则
  # 'array-element-newline': ['error', 'consistent']
  # 防止因为自动换行造成的报错
  # 'implicit-arrow-linebreak': ['off', 'beside']
  # 简化代码，忽略迷惑的箭头函数提示
  # 'no-confusing-arrow': 'off'
